modLoader="javafml"
loaderVersion="[25,)"
logoFile="clayball.png"
	
[[mods]]
	modId="clayconversion"
	version="1.4"
	displayName="Clay Conversion"
	displayURL="https://minecraft.curseforge.com/projects/clay-conversion"
	authors="Kaden"
	description='Convert your clay blocks into clay balls easily with this mod!'