modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory (24 is current forge version)
[[mods]] #mandatory
	modId="clayconversion" #mandatory
	version="1.3" #mandatory
	displayName="Clay Conversion" #mandatory
	displayURL="https://www.curseforge.com/minecraft/mc-mods/clay-conversion" #optional
	logoFile="clayball.png" #optional
	credits="" #optional
	authors="Kaden Sharpin" #optional
	description='''Convert your clay blocks into clay balls easily with this mod!


'''
[[dependencies.clayconversion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13,1.13.2]"
    ordering="NONE"
    side="BOTH"