modLoader="javafml"
loaderVersion="[32,)"
[[mods]]
	modId="clayconversion" 
	version="1.0"
	displayName="Clay Conversion"
	logoFile="clayball.png"
	authors="Kaden"
	description='''Convert your clay blocks into clay balls easily with this mod!'''