modLoader="javafml"
loaderVersion="[33,)"
logoFile="clayball.png"
license="All rights reserved"
issueTrackerURL="https://github.com/KadenS2005/Clay-Conversion/issues"
[[mods]]
	modId="clayconversion"
	version="1.4"
	displayName="Clay Conversion"
	updateJSONURL="https://raw.githubusercontent.com/KadenS2005/Clay-Conversion/master/update.json"
	displayURL="https://minecraft.curseforge.com/projects/clay-conversion"
	authors="Kaden"
	description='Convert your clay blocks into clay balls easily with this mod!'